name: Linux Build

on: [push, workflow_dispatch]

jobs:
  build-opencl:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: APT update
      run: sudo apt update
    - name: APT install
      run: sudo apt install ocl-icd-opencl-dev
    - name: make all
      run: make all
    - uses: actions/upload-artifact@v4
      with:
        name: TeamSpeakHasher-Linux-Bin
        path: TeamSpeakHasher

  build-cuda:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install CUDA Toolkit
      uses: Jimver/cuda-toolkit@v0.2.19
      with:
        cuda: '12.6.3'
        method: 'network'
        sub-packages: '["nvcc", "cudart-dev"]'
    - name: APT update
      run: sudo apt update
    - name: APT install
      run: sudo apt install ocl-icd-opencl-dev
    - name: make all (OpenCL + CUDA)
      run: make all
    - uses: actions/upload-artifact@v4
      with:
        name: TeamSpeakHasher-Linux-CUDA-Bin
        path: TeamSpeakHasher
